#!/bin/bash
# PreToolUse Write|Edit hook: block AI-attribution watermarks.
# Reads $CLAUDE_TOOL_INPUT (JSON) and looks at content/new_string.
# CLAUDE.md explicitly forbids Co-Authored-By, "Generated with Claude", robot emoji.

# Tool input arrives via stdin as JSON for Write/Edit hooks.
INPUT=$(cat)

# Pull the strings most likely to contain watermarks. We grep the raw JSON;
# false positives are acceptable since the model will simply rewrite.
PATTERNS=(
  'Co-Authored-By: Claude'
  'Co-authored-by: Claude'
  '🤖 Generated with'
  'Generated with \[Claude'
  'Generated by Claude'
  'noreply@anthropic.com'
)

for pattern in "${PATTERNS[@]}"; do
  if echo "$INPUT" | grep -qE "$pattern"; then
    echo "BLOCKED: write contains AI attribution pattern: '$pattern'" >&2
    echo "Project policy (CLAUDE.md) forbids AI watermarks. Remove and retry." >&2
    exit 2
  fi
done

exit 0
